name: Docker Image CI cuttingedge

on:
  push:
    branches: [ "cuttingedge" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-22.04

    steps:      
      - name: Checkout
        uses: actions/checkout@v6

      # https://github.com/docker/setup-qemu-action#usage
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.7.0

      # https://github.com/marketplace/actions/docker-setup-buildx
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3.12.0
      
      # https://github.com/docker/login-action#docker-hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      # https://github.com/docker/build-push-action#multi-platform-image
      - name: Build and push API
        uses: docker/build-push-action@v6.18.0
        with:
          context: ./
          file: ./Dockerfile
          #platforms: linux/amd64,linux/amd64/v2,linux/amd64/v3,linux/arm64,linux/arm/v7
          platforms: linux/amd64,linux/amd64/v2,linux/amd64/v3,linux/arm64,linux/arm/v7
          pull: true
          push: true
          tags: |
            glax/tranga-api:cuttingedge
